### ISSUE TITLE
add me to owners of nupic-community

### ISSUE THREAD

**Issue by breznak** [nupic-community/nupic.studio#24]
@rhyolight @david-ragazzi I'd like to try a fork of nupic in nupic-community/nupic.bio 
which should be an experimental repo for:
* simplified, cleaned-up
* more Whitepaper/biologically accurate
* python only, not focusing on speed in first place
* simple reference implementation for learning HTM/CLA

but I can't create/fork nupic in nupic-community as I'm not an owner. Please add me there

**Comment by david-ragazzi** [comment]
:+1: Of course!

**Comment by breznak** [comment]
muito obrigado :tada:

**Comment by david-ragazzi** [comment]
> muito obrigado :tada:

De nada!

**Comment by david-ragazzi** [comment]
> muito obrigado :tada:

De nada, meu amigo!
