### ISSUE TITLE
the error about installing nupic_studio

### ISSUE THREAD

**Issue by wanghouzhi** [nupic-community/nupic.studio#30]
hi everyone 
   I’m trying to install nupic_studio following as https://github.com/nupic-community/nupic.studio , when i run the command  “pip install nupic_studio” ,i get the error :

Running setup.py egg_info for package nupic-studio

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/tmp/pip-build-root/nupic-studio/setup.py", line 37, in <module>

        execfile(os.path.join(REPO_DIR, "nupic_studio", "__init__.py"), {}, properties)

      File "/tmp/pip-build-root/nupic-studio/nupic_studio/__init__.py", line 30, in <module>

        versionFound = nupic.__version__

    AttributeError: 'module' object has no attribute '__version__'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-root/nupic-studio/setup.py", line 37, in <module>

    execfile(os.path.join(REPO_DIR, "nupic_studio", "__init__.py"), {}, properties)

  File "/tmp/pip-build-root/nupic-studio/nupic_studio/__init__.py", line 30, in <module>

    versionFound = nupic.__version__

AttributeError: 'module' object has no attribute ‘__version__'

I install it on CentOS6.5, and install nupic using
pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.1.5-cp27-none-linux_x86_64.whl
pip install nupic

I look at the nupic.__version__ on python shell ,the result is :

[root@dev-whz ~]# python
Python 2.7.6 (default, Sep  8 2015, 10:11:11) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nupic
>>> nupic.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
>>> 
Can somebody offer any suggestions to fix the error ?  and it looks like depending on an older
version of NuPIC

**Comment by rhyolight** [comment]
Related: https://github.com/numenta/nupic/issues/2555#issuecomment-138593882

**Comment by david-ragazzi** [comment]
@wanghouzhi Please re-pip nupic.studio again and let me know that the problem persists.

**Comment by wanghouzhi** [comment]
@David Ragazzi ， i am sorry ,i just saw the email ,  I have tried again , it is ok .    
thank you !
but i run the nupic_studio ,i got the error :
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

Process:               Python [2798]
Path:                  /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.10 (2.7.10)
Code Type:             X86-64 (Native)
Parent Process:        bash [2656]
Responsible:           Terminal [265]
User ID:               501

Date/Time:             2015-09-11 15:19:07.577 +0800
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        02AEC88F-7E10-3F0D-F143-CF7418C99542

Sleep/Wake UUID:       29BDD732-75A8-4DB1-B881-DBD7FABF2BF9

Time Awake Since Boot: 140000 seconds
Time Since Wake:       100000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8f04c286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff939d2b53 abort + 129
2   org.python.python             	0x00000001132df621 Py_FatalError + 49
3   org.python.python             	0x00000001132de68c PyThreadState_Get + 44
4   org.python.python             	0x00000001132da97b Py_InitModule4_64 + 75
5   _math.so                      	0x0000000112981e40 init_math + 864
6   org.python.python             	0x000000010c467327 _PyImport_LoadDynamicModule + 140
7   org.python.python             	0x000000010c465c39 imp_load_module + 243
8   org.python.python             	0x000000010c452979 PyEval_EvalFrameEx + 14227


can you solve my question ？

**Comment by rhyolight** [comment]
On Fri, Sep 11, 2015 at 12:23 AM, wanghouzhi <notifications@github.com> wrote:
>
> Fatal Python error: PyThreadState_Get: no current thread
> Abort trap: 6

This usually means you have two or more versions of Python installed
on your system, and there is a mismatch somewhere. The only known
solution is to uninstall one or more version until you have one single
version of Python on your system.


---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by wanghouzhi** [comment]
thanks Matthew Taylor!
> 在 2015年9月11日，下午10:32，Matthew Taylor <notifications@github.com> 写道：
>
